### ISSUE TITLE
您好，是否可以将这些代码贡献到Microsoft的Visual Studio Tools For AI的开源样例库中？

### ISSUE THREAD

**Issue by wangcunxiang** [jxwuyi/AtNRE#1]
这是一个由MSRA主导的，为丰富Visual Studio Tools For AI开源样例库而开展的一个学生项目。项目地址是 https://github.com/Microsoft/samples-for-ai 。我们将注明原作者及license。万分感谢。

**Comment by jxwuyi** [comment]
所以我需要怎么整理？

**Comment by wangcunxiang** [comment]
不好意思，通知邮件进了junkbox，导致现在才看到您的回复。不需要您来整理，我们自己就可以。万分感谢。
